version: "2"

volumes:
  seed-mysql-data:
    driver: local

  seed-redis-data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: seed-mysql
    volumes:
      - seed-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=seed
      - MYSQL_DATABASE=seed
      - MYSQL_USER=seed
      - MYSQL_PASSWORD=seed

  cache:
    image: redis:4.0
    container_name: seed-redis
    command: --appendonly yes
    volumes:
      - seed-redis-data:/data
    ports:
      - "6380:6379"

  app:
    image: ambientum/php:7.3-nginx
    container_name: seed-app
    volumes:
      - .:/var/www/app
    ports:
      - "8081:8080"
    environment:
      XDEBUG_ENABLED: "true"
    # command: start.sh
    links:
      - mysql
      - cache
