version: "2"

volumes:
  prediction-mysql-data:
    driver: local

  prediction-redis-data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: prediction-mysql
    volumes:
      - prediction-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=prediction
      - MYSQL_DATABASE=prediction
      - MYSQL_USER=prediction
      - MYSQL_PASSWORD=prediction

  cache:
    image: redis:4.0
    container_name: prediction-redis
    command: --appendonly yes
    volumes:
      - prediction-redis-data:/data
    ports:
      - "6380:6379"

  app:
    image: ambientum/php:7.3-nginx
    container_name: prediction-app
    volumes:
      - .:/var/www/app
    ports:
      - "8081:8080"
    environment:
      XDEBUG_ENABLED: "true"
    # command: start.sh
    links:
      - mysql
      - cache
